import type { ComponentLibraryEntry } from './component-document'
import { COMPONENT_PACKAGE_VERSION } from './component-document'
import { COMPONENT_VISUAL_VERSION } from '../../component-system/visual'

export const SAMPLE_STORAGE_TANK_ID = 'component-smart-storage-tank'

export const sampleStorageTankEntry: ComponentLibraryEntry = {
  version: COMPONENT_PACKAGE_VERSION,
  id: SAMPLE_STORAGE_TANK_ID,
  definition: {
    type: 'custom.tank.smart-storage',
    title: '智能立式储罐',
    category: '容器设备',
    description: '工业级立式金属储罐，支持自底向上液位动态生长、柱面金属渐变、超高液位光晕报警及正交出料管道自动吸附。',
    size: {
      defaultWidth: 320,
      defaultHeight: 280,
      minWidth: 160,
      minHeight: 140,
    },
    attributes: {},
    properties: {
      level: {
        title: '液位高度 (%)',
        kind: 'number',
        defaultValue: 65,
        bindable: true,
      },
      alarmThreshold: {
        title: '报警阈值 (%)',
        kind: 'number',
        defaultValue: 85,
        bindable: true,
      },
    },
    actions: {},
    events: {},
    anchors: [
      {
        id: 'inlet',
        title: '顶部进料口',
        position: { x: 0.28, y: 0.08 },
        outward: { x: 0, y: -1 },
        role: 'target',
      },
      {
        id: 'outlet',
        title: '右侧出料口',
        position: { x: 0.47, y: 0.7 },
        outward: { x: 1, y: 0 },
        role: 'source',
      },
      {
        id: 'drain',
        title: '底部排污口',
        position: { x: 0.28, y: 0.95 },
        outward: { x: 0, y: 1 },
        role: 'source',
      },
    ],
  },
  visual: {
    version: COMPONENT_VISUAL_VERSION,
    mode: 'composite',
    designSize: { width: 320, height: 280 },
    layers: [
      // 1. 左支脚
      {
        id: 'layer-leg-left',
        name: '左侧支腿',
        kind: 'vector',
        primitive: 'rect',
        parentId: null,
        visible: true,
        opacity: 1,
        transform: { x: 45, y: 220, width: 14, height: 40, rotation: 0, scaleX: 1, scaleY: 1 },
        style: {
          fill: '#475569',
          stroke: '#334155',
          strokeWidth: 1,
          cornerRadius: 3,
        },
      },
      // 2. 右支脚
      {
        id: 'layer-leg-right',
        name: '右侧支腿',
        kind: 'vector',
        primitive: 'rect',
        parentId: null,
        visible: true,
        opacity: 1,
        transform: { x: 121, y: 220, width: 14, height: 40, rotation: 0, scaleX: 1, scaleY: 1 },
        style: {
          fill: '#475569',
          stroke: '#334155',
          strokeWidth: 1,
          cornerRadius: 3,
        },
      },
      // 3. 金属罐体圆柱主体 (5色标线性渐变高光柱面 + 投影深度)
      {
        id: 'layer-tank-body',
        name: '金属罐体外壳',
        kind: 'vector',
        primitive: 'rect',
        parentId: null,
        visible: true,
        opacity: 1,
        transform: { x: 30, y: 35, width: 120, height: 195, rotation: 0, scaleX: 1, scaleY: 1 },
        style: {
          fill: '#64748b',
          stroke: '#1e293b',
          strokeWidth: 2,
          cornerRadius: 16,
          gradient: {
            type: 'linear',
            angle: 0,
            stops: [
              { offset: 0, color: '#334155' },
              { offset: 0.22, color: '#94a3b8' },
              { offset: 0.55, color: '#64748b' },
              { offset: 0.82, color: '#475569' },
              { offset: 1, color: '#1e293b' },
            ],
          },
          shadow: {
            color: 'rgba(0, 0, 0, 0.35)',
            blur: 14,
            offsetX: 0,
            offsetY: 8,
          },
        },
      },
      // 4. 视镜视窗背景槽
      {
        id: 'layer-gauge-bg',
        name: '视镜视窗背景',
        kind: 'vector',
        primitive: 'rect',
        parentId: null,
        visible: true,
        opacity: 1,
        transform: { x: 74, y: 65, width: 32, height: 140, rotation: 0, scaleX: 1, scaleY: 1 },
        style: {
          fill: '#090d16',
          stroke: '#1e293b',
          strokeWidth: 2,
          cornerRadius: 8,
        },
      },
      // 5. 动态液位层 (origin: 'bottom-center'，垂直线性渐变水体)
      {
        id: 'layer-liquid-fill',
        name: '液体液位层',
        kind: 'vector',
        primitive: 'rect',
        parentId: null,
        origin: 'bottom-center',
        visible: true,
        opacity: 0.92,
        transform: { x: 78, y: 69, width: 24, height: 132, rotation: 0, scaleX: 1, scaleY: 0.65 },
        style: {
          fill: '#0284c7',
          stroke: '#38bdf8',
          strokeWidth: 1,
          cornerRadius: 4,
          gradient: {
            type: 'linear',
            angle: 90,
            stops: [
              { offset: 0, color: '#38bdf8' },
              { offset: 0.45, color: '#0284c7' },
              { offset: 1, color: '#0369a1' },
            ],
          },
          shadow: {
            color: 'rgba(56, 189, 248, 0.6)',
            blur: 10,
            offsetX: 0,
            offsetY: 0,
          },
        },
      },
      // 6. 玻璃高光反光
      {
        id: 'layer-glass-reflection',
        name: '视镜玻璃高光',
        kind: 'vector',
        primitive: 'rect',
        parentId: null,
        visible: true,
        opacity: 0.4,
        transform: { x: 80, y: 69, width: 6, height: 132, rotation: 0, scaleX: 1, scaleY: 1 },
        style: {
          fill: '#ffffff',
          stroke: '',
          strokeWidth: 0,
          cornerRadius: 3,
        },
      },
      // 6.1 视窗工业刻度标尺 (拉伸自适应动态增加刻度)
      {
        id: 'layer-tank-scale',
        name: '视窗计量刻度尺',
        kind: 'vector',
        primitive: 'scale',
        parentId: null,
        visible: true,
        opacity: 0.85,
        transform: { x: 102, y: 69, width: 24, height: 132, rotation: 0, scaleX: 1, scaleY: 1 },
        scaleMode: 'auto',
        tickSpacing: 22,
        subDivisions: 2,
        tickLength: 6,
        subTickLength: 3,
        tickPlacement: 'right',
        showAxis: true,
        showLabels: true,
        labelStart: 0,
        minTickValue: 5,
        labelDirection: 'bottomUp',
        labelFontSize: 8,
        labelColor: '#94a3b8',
        style: {
          fill: '',
          stroke: '#94a3b8',
          strokeWidth: 1.5,
          lineCap: 'butt',
        },
      },
      // 7. 罐顶报警灯 (带强力 Glow 光晕)
      {
        id: 'layer-alarm-lamp',
        name: '高位报警灯',
        kind: 'vector',
        primitive: 'ellipse',
        parentId: null,
        visible: true,
        opacity: 1,
        transform: { x: 80, y: 16, width: 20, height: 20, rotation: 0, scaleX: 1, scaleY: 1 },
        style: {
          fill: '#ef4444',
          stroke: '#b91c1c',
          strokeWidth: 2,
          shadow: {
            color: '#ef4444',
            blur: 18,
            offsetX: 0,
            offsetY: 0,
          },
        },
      },
      // 8. 出料管线 (带指示箭头)
      {
        id: 'layer-outlet-pipe',
        name: '出料管线',
        kind: 'vector',
        primitive: 'line',
        parentId: null,
        visible: true,
        opacity: 1,
        points: [150, 195, 220, 195, 220, 245, 290, 245],
        transform: { x: 0, y: 0, width: 290, height: 250, rotation: 0, scaleX: 1, scaleY: 1 },
        style: {
          fill: '',
          stroke: '#38bdf8',
          strokeWidth: 6,
          lineCap: 'round',
          endMarker: 'arrow',
        },
      },
      // 9. 液位读数文本
      {
        id: 'layer-level-label',
        name: '液位读数',
        kind: 'text',
        parentId: null,
        text: '65.0 %',
        visible: true,
        opacity: 1,
        transform: { x: 60, y: 215, width: 60, height: 18, rotation: 0, scaleX: 1, scaleY: 1 },
        style: {
          fill: '#e2e8f0',
          fontFamily: 'monospace',
          fontSize: 12,
          fontStyle: 'normal',
          align: 'center',
          verticalAlign: 'middle',
          lineHeight: 1.2,
        },
      },
    ],
    rules: [
      {
        id: 'rule-high-level-alarm',
        enabled: true,
        propertyKey: 'level',
        operator: 'greaterOrEqual',
        compareValue: 85,
        layerId: 'layer-alarm-lamp',
        target: 'visible',
        value: true,
      },
    ],
    animations: [],
  },
  status: 'ready',
  implementationDraft: '// 智能立式储罐：已完成可视化图元组合与物理吸附绑定\n',
  updatedAt: '2026-09-23T12:00:00.000Z',
  builtIn: false,
}
